icmp_interval = "2s"
icmp_timeout = "250ms"
burst_size =3 
burst_interval = "10s"
#up_action = ""
#down_action = ""

[[interfaces]]
name = "ens33"
table = 2
minimum_up = 1
metric = 3


[[interfaces.hosts]]
name = "Google"
host = "8.8.8.8"

[[interfaces.hosts]]
name = "Cloudflare"
host = "1.1.1.1"

[[interfaces.hosts]]
name = "Cloudflare"
host = "2606:4700:4700::1111"

[[interfaces]]
name = "ens34"
table = 3
metric = 2
minimum_up = 1

[[interfaces.hosts]]
name = "Cloudflare"
host = "1.0.0.1"
