name: Static Analysis

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.19]
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      
      - name: Print staticcheck version
        run: staticcheck -version

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Install enumcheck
        run: go install loov.dev/enumcheck@latest

      - name: Run enumcheck
        run: enumcheck ./...

      - name: Run go vet
        run: go vet ./...

      - name: Run CI script
        run: ./.github/workflows/script.sh

      - name: Build Hodos
        run: go build ./cmd/hodos/

      - name: Install tomlv
        run: go install github.com/BurntSushi/toml/cmd/tomlv@latest

      - name: Generate default TOML configuration
        run: ./hodos -example > hodos.toml

      - name: Verify default TOML configuration
        run: tomlv ./hodos.toml
